# Generated by Django 5.1.1 on 2024-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('salary', models.PositiveIntegerField()),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
